version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: prontuario-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=prontuario
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./Backend:/app/
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: prontuario-db
    environment:
      POSTGRES_DB: prontuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
