services:
  backend:
    build:
      context: ./backend  # Só envia o conteúdo da pasta backend
    container_name: prontuario-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/prontuario
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: prontuario-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prontuario
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
